language: ruby
rvm:
    - 2.4
branches:
  only:
    - gh-pages

before_install:
    - gem install jekyll -v 3.3.1
    - gem install jekyll-redirect-from
    - gem install s3_website

install: jekyll build

script: s3_website push

