# Site settings
title: Tankery
subtitle: "Create stuff delights people."
email: tankery.chen@gmail.com
url: https://tankery.me
baseurl: ""
description: "Personal site of Tankery Chen the Android developer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Tankery Chen
  location: Email
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/tankery
  - title: stack-overflow
    url: http://stackoverflow.com/users/1038900
  - title: google-plus
    url: https://plus.google.com/+TankeryChen
  - title: weibo
    url: http://weibo.com/u/1658528753
  # - title: bitbucket
  #   url: http://bitbucket.org/tankery

# Postal address (add as many lines as necessary)
address:
  - line: tankery.chen@gmail.com

# Credits content
credits: 'Made by Jekyll theme based on <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - main_sections
  - portfolios

# Plugins
gems:
  - jekyll-redirect-from
